

CREATE TABLE "app_post" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "body" varchar(144) NOT NULL, "create_at" timestamp with time zone NOT NULL, "author_id" bigint NOT NULL) partition by range(create_at);
ALTER TABLE "app_post" ADD CONSTRAINT "app_postmodel_author_id_87e1d289_fk_app_customuser_id" FOREIGN KEY ("author_id") REFERENCES "app_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_postmodel_author_id_87e1d289" ON "app_post" ("author_id");



CREATE TABLE public.app_postmodel (
    id bigint NOT NULL,
    body character varying(144) NOT NULL,
    create_at timestamp with time zone NOT NULL,
    author_id bigint NOT NULL
)
PARTITION BY RANGE (create_at);

ALTER TABLE public.app_postmodel OWNER TO farhad;


ALTER TABLE public.app_postmodel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_postmodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.app_postmodel
    ADD CONSTRAINT app_postmodel_pkey PRIMARY KEY (id, create_at);

CREATE INDEX app_postmodel_author_id_dc4785e7 ON ONLY public.app_postmodel USING btree (author_id);

ALTER TABLE public.app_postmodel
    ADD CONSTRAINT app_postmodel_author_id_dc4785e7_fk_app_customuser_id FOREIGN KEY (author_id) REFERENCES public.app_customuser(id) DEFERRABLE INITIALLY DEFERRED;
