# Generated by Django 4.2.4 on 2023-09-15 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import psqlextra.manager.manager


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_followership_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(max_length=144)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
