# Generated by Django 4.2.4 on 2023-09-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_postpartition"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post2Partition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(max_length=144)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "app_postmodel_default",
                "managed": False,
            },
        ),
    ]
